using DAL.Entities;

namespace DAL.DbContext
{
    public static class SeedReviews
    {
        public static void SeedData(ApplicationDbContext context)
        {
            if (!context.Reviews.Any())
            {
                context.Reviews.AddRange(new List<Review>
                {
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                    new Review { IsPositive = false, ReviewText = "Completely disappointed with this product."},
                    new Review { IsPositive = false, ReviewText = "Would not buy this again."},
                    new Review { IsPositive = false, ReviewText = "Worst purchase I've ever made."},
                    new Review { IsPositive = false, ReviewText = "Not worth the money."},
                    new Review { IsPositive = false, ReviewText = "The item broke after one use."},
                    new Review { IsPositive = true, ReviewText = "The best I've used so far."},
                    new Review { IsPositive = true, ReviewText = "Exceeded my expectations."},
                    new Review { IsPositive = true, ReviewText = "Will definitely buy again."},
                    new Review { IsPositive = true, ReviewText = "Fast delivery and great quality."},
                    new Review { IsPositive = true, ReviewText = "Product works perfectly."},
                    new Review { IsPositive = false, ReviewText = "Definitely not recommended."},
                    new Review { IsPositive = true, ReviewText = "Customer service was excellent."},
                    new Review { IsPositive = false, ReviewText = "Feels cheap and unreliable."},
                    new Review { IsPositive = true, ReviewText = "Highly recommend to everyone."},
                    new Review { IsPositive = false, ReviewText = "Very poor quality and late delivery."},
                    new Review { IsPositive = true, ReviewText = "Five stars without a doubt."},
                    new Review { IsPositive = true, ReviewText = "Fantastic experience from start to finish."},
                    new Review { IsPositive = false, ReviewText = "Customer service was terrible."},
                    new Review { IsPositive = false, ReviewText = "Did not meet expectations."},
                    new Review { IsPositive = true, ReviewText = "Absolutely loved this product!"},
                });

                context.SaveChanges();
            }
        }
    }
}
